//   ==================================================================
//   >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
//   ------------------------------------------------------------------
//   Copyright (c) 2006-2011 by Lattice Semiconductor Corporation
//   ------------------------------------------------------------------
//   ALL RIGHTS RESERVED
//
//   IMPORTANT: THIS FILE IS AUTO-GENERATED BY THE LATTICEMICO SYSTEM.
//
//   Permission:
//
//      Lattice Semiconductor grants permission to use this code
//      pursuant to the terms of the Lattice Semiconductor Corporation
//      Open Source License Agreement.
//
//   Disclaimer:
//
//      Lattice Semiconductor provides no warranty regarding the use or
//      functionality of this code. It is the user's responsibility to
//      verify the user’s design for consistency and functionality through
//      the use of formal verification methods.
//
//   --------------------------------------------------------------------
//
//                  Lattice Semiconductor Corporation
//                  5555 NE Moore Court
//                  Hillsboro, OR 97214
//                  U.S.A
//
//                  TEL: 1-800-Lattice (USA and Canada)
//                         503-286-8001 (other locations)
//
//                  web: http://www.latticesemi.com/
//                  email: techsupport@latticesemi.com
//
//   --------------------------------------------------------------------
//
//      Project:           AP1220_controller
//      File:              AP1220_controller_inst.v
//      Date:              Sun, 10 Nov 2013 23:41:19 PST
//      Version:           2.1
//      Targeted Family:   MachXO2
//
//   =======================================================================

// Attn : This file is used for VHDL Wrapper

AP1220_controller_vhd AP1220_controller_u ( 
.clk_i(clk_i),
.reset_n(reset_n)
, .LEDPIO_OUT(LEDPIO_OUT) // [4-1:0]
, .uartSIN(uartSIN) // 
, .uartSOUT(uartSOUT) // 
, .SPI_controllerclk(SPI_controllerclk) // 
, .SPI_controllerrst(SPI_controllerrst) // 
, .SPI_controllerslv_adr(SPI_controllerslv_adr) // [32-1:0]
, .SPI_controllerslv_master_data(SPI_controllerslv_master_data) // [8-1:0]
, .SPI_controllerslv_slave_data(SPI_controllerslv_slave_data) // [8-1:0]
, .SPI_controllerslv_strb(SPI_controllerslv_strb) // 
, .SPI_controllerslv_cyc(SPI_controllerslv_cyc) // 
, .SPI_controllerslv_ack(SPI_controllerslv_ack) // 
, .SPI_controllerslv_err(SPI_controllerslv_err) // 
, .SPI_controllerslv_rty(SPI_controllerslv_rty) // 
, .SPI_controllerslv_sel(SPI_controllerslv_sel) // [3:0] 
, .SPI_controllerslv_we(SPI_controllerslv_we) // 
, .SPI_controllerslv_bte(SPI_controllerslv_bte) // [1:0] 
, .SPI_controllerslv_cti(SPI_controllerslv_cti) // [2:0] 
, .SPI_controllerslv_lock(SPI_controllerslv_lock) // 
, .SPI_controllerintr_active_high(SPI_controllerintr_active_high) // 
);
